MOUSEKEY_ENABLE = yes    # Mouse keys
RGBLIGHT_ENABLE = yes    # Enable WS2812 RGB underlight.
OLED_ENABLE     = yes
#OLED_DRIVER     = SSD1306
LTO_ENABLE      = yes
COMBO_ENABLE    = yes
#POINTING_DEVICE_ENABLE = yes
#POINTING_DEVICE_DRIVER = cirque_pinnacle_i2c
#DYNAMIC_TAPPING_TERM_ENABLE = yes
#TAP_DANCE_ENABLE = yes
#CONVERT_TO=blok     Only for RP2040 boards
